#!/bin/bash

# Create database and populate with design docs.
echo "Note: tests assume couchdb availabable at http://127.0.0.1:5984"
curl -X PUT http://127.0.0.1:5984/test_documents
curl -X PUT http://127.0.0.1:5984/test_documents/_design/pages -d @../design_docs/pages.json

# Run tests
NODE_ENV=test  bin/expresso test.js

# Clean up
curl -X DELETE http://127.0.0.1:5984/test_documents
